---
title: "Demo"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tidyverse)
library(irma)
```


Make a dataset:

```{r}
n <- 80
p <- 0.2
se <- 0.8
sp <- 0.7

dat <- make_data(n, p, se, sp)
dat
```

Check implied parameters (consequence of rounding):

```{r}
dat %>% get_param_from_data()
```

Plot it

```{r}
dat %>%
  mutate(
    test=factor(test, labels=c("T-","T+")),
    disease=factor(disease, labels=c("D-","D+"))
  ) %>%
  autoplot.irma_data(fill_by=disease)
```

Or the other way:

```{r}
dat %>%
  mutate(
    test=factor(test, labels=c("T-","T+")),
    disease=factor(disease, labels=c("D-","D+"))
  ) %>%
  autoplot.irma_data(fill_by=test)
```



TODO:
- [ ] Zeallotify
- [ ] importFrom crazyness
- [ ] Solve the S3 thing: making data an object of class irma breaks everything

TODO shiny:
- [ ] Allow log10 variations for total
